# Generated by Django 3.2.2 on 2021-07-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default=10, max_length=225),
            preserve_default=False,
        ),
    ]
